// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usavnidrbrouewtbesby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzYXZuaWRyYnJvdWV3dGJlc2J5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NzUwNzMsImV4cCI6MjA2NzM1MTA3M30.bBknCF2GhL_ZA0cst0YPbNFSE1BM71CbcZ8o0LsyOec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});